apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-sql-configmap
data:
  init.sql: |
    -- Create the employees table if it doesn't exist
    CREATE TABLE IF NOT EXISTS employees (
      employee_id INTEGER PRIMARY KEY AUTOINCREMENT,
      first_name TEXT,
      last_name TEXT,
      department TEXT,
      job_title TEXT,
      email TEXT,
      phone_number TEXT,
      hire_date DATE,
      status TEXT
    );

  index.php: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Employees List</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                padding: 0;
                background-color: #f4f4f4;
            }
            h1 {
                color: #333;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }
            table, th, td {
                border: 1px solid #ddd;
            }
            th, td {
                padding: 12px;
                text-align: left;
            }
            th {
                background-color: #f2f2f2;
            }
            input[type="text"] {
                padding: 8px;
                width: 300px;
                margin: 10px 0;
            }
        </style>
        <script>
            // Search Functionality
            function searchUsers() {
                var input, filter, table, tr, td, i, txtValue;
                input = document.getElementById("searchInput");
                filter = input.value.toUpperCase();
                table = document.getElementById("employeesTable");
                tr = table.getElementsByTagName("tr");

                for (i = 1; i < tr.length; i++) {
                    tr[i].style.display = "none";
                    td = tr[i].getElementsByTagName("td");
                    for (var j = 0; j < td.length; j++) {
                        if (td[j]) {
                            txtValue = td[j].textContent || td[j].innerText;
                            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                tr[i].style.display = "";
                                break;
                            }
                        }
                    }
                }
            }
        </script>
    </head>
    <body>

    <h1>Employees List</h1>

    <!-- Search Box -->
    <input type="text" id="searchInput" onkeyup="searchUsers()" placeholder="Search for names or emails..">

    <?php
    // Connection details
    $dbname = '/var/www/html/employees.db'; // Path to your SQLite database file

    // Create a new PDO instance for SQLite
    $dsn = "sqlite:$dbname";

    try {
        // Connect to SQLite database
        $pdo = new PDO($dsn);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // Fetch data from the employees table
        $stmt = $pdo->query("SELECT * FROM employees");
        $employees = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Start of table
        echo "<table id='employeesTable'>";
        echo "<tr><th>ID</th><th>First Name</th><th>Last Name</th><th>Department</th><th>Job Title</th><th>Email</th><th>Phone</th><th>Hire Date</th><th>Status</th></tr>";

        // Display the employees in the table
        foreach ($employees as $employee) {
            echo "<tr>
                    <td>{$employee['employee_id']}</td>
                    <td>{$employee['first_name']}</td>
                    <td>{$employee['last_name']}</td>
                    <td>{$employee['department']}</td>
                    <td>{$employee['job_title']}</td>
                    <td>{$employee['email']}</td>
                    <td>{$employee['phone_number']}</td>
                    <td>{$employee['hire_date']}</td>
                    <td>{$employee['status']}</td>
                  </tr>";
        }

        echo "</table>";

    } catch (PDOException $e) {
        echo "Error: " . $e->getMessage();
    }
    ?>

    </body>
    </html>
