apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-sql-configmap
data:
  init-db: |
    #!/usr/bin/env php
    <?php
    $dbname = '/var/www/html/employees.db';

    try {
        $pdo = new PDO("sqlite:$dbname");
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        
        // Create the employees table
        $sql = "CREATE TABLE IF NOT EXISTS employees (
            employee_id INTEGER PRIMARY KEY AUTOINCREMENT,
            first_name TEXT,
            last_name TEXT,
            department TEXT,
            job_title TEXT,
            email TEXT,
            phone_number TEXT,
            hire_date DATE,
            status TEXT
        )";
        $pdo->exec($sql);
        
        // Insert initial data
        $insert_sql = "INSERT INTO employees (first_name, last_name, department, job_title, email, phone_number, hire_date, status) VALUES
            ('John', 'Doe', 'IT', 'Software Engineer', 'john.doe@example.com', '1234567890', '2023-01-15', 'Active'),
            ('Jane', 'Smith', 'HR', 'HR Manager', 'jane.smith@example.com', '0987654321', '2023-01-20', 'Active'),
            ('Mark', 'Brown', 'Sales', 'Sales Representative', 'mark.brown@example.com', '1122334455', '2023-01-25', 'Inactive')";
        $pdo->exec($insert_sql);
        
        echo "SQLite database created with table 'employees' and initial data inserted.";
    } catch (PDOException $e) {
        echo "Database error: " . $e->getMessage();
    }
    ?>

  index.php: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Employees List</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                padding: 0;
                background-color: #f4f4f4;
            }
            h1 {
                color: #333;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }
            table, th, td {
                border: 1px solid #ddd;
            }
            th, td {
                padding: 12px;
                text-align: left;
            }
            th {
                background-color: #f2f2f2;
            }
            input[type="text"] {
                padding: 8px;
                width: 300px;
                margin: 10px 0;
            }
        </style>
        <script>
            // Search Functionality
            function searchUsers() {
                var input, filter, table, tr, td, i, txtValue;
                input = document.getElementById("searchInput");
                filter = input.value.toUpperCase();
                table = document.getElementById("employeesTable");
                tr = table.getElementsByTagName("tr");

                for (i = 1; i < tr.length; i++) {
                    tr[i].style.display = "none";
                    td = tr[i].getElementsByTagName("td");
                    for (var j = 0; j < td.length; j++) {
                        if (td[j]) {
                            txtValue = td[j].textContent || td[j].innerText;
                            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                tr[i].style.display = "";
                                break;
                            }
                        }
                    }
                }
            }
        </script>
    </head>
    <body>
        <h1>Employees List</h1>
        <!-- Search Box -->
        <input type="text" id="searchInput" onkeyup="searchUsers()" placeholder="Search for names or emails..">
        <table id="employeesTable">
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Department</th>
                <th>Job Title</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Hire Date</th>
                <th>Status</th>
            </tr>
        </table>
    </body>
    </html>
