apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-sql-configmap
data:
  init.sql: |
    -- Create the employees table
    CREATE TABLE employees (
      employee_id SERIAL PRIMARY KEY,
      first_name VARCHAR(100),
      last_name VARCHAR(100),
      department VARCHAR(100),
      job_title VARCHAR(100),
      email VARCHAR(100),
      phone_number VARCHAR(15),
      hire_date DATE,
      status VARCHAR(20)
    );

  index.php: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Employees List</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                padding: 0;
                background-color: #f4f4f4;
            }
            h1 {
                color: #333;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }
            table, th, td {
                border: 1px solid #ddd;
            }
            th, td {
                padding: 12px;
                text-align: left;
            }
            th {
                background-color: #f2f2f2;
            }
            input[type="text"] {
                padding: 8px;
                width: 300px;
                margin: 10px 0;
            }
        </style>
        <script>
            // Search Functionality
            function searchUsers() {
                var input, filter, table, tr, td, i, txtValue;
                input = document.getElementById("searchInput");
                filter = input.value.toUpperCase();
                table = document.getElementById("employeesTable");
                tr = table.getElementsByTagName("tr");

                for (i = 1; i < tr.length; i++) {
                    tr[i].style.display = "none";
                    td = tr[i].getElementsByTagName("td");
                    for (var j = 0; j < td.length; j++) {
                        if (td[j]) {
                            txtValue = td[j].textContent || td[j].innerText;
                            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                tr[i].style.display = "";
                                break;
                            }
                        }
                    }
                }
            }
        </script>
    </head>
    <body>

    <h1>Employees List</h1>

    <!-- Search Box -->
    <input type="text" id="searchInput" onkeyup="searchUsers()" placeholder="Search for names or emails..">

    <?php
    // Connection details
    $host = getenv('DB_HOST');
    $dbname = getenv('DB_NAME');
    $user = getenv('DB_USER');
    $password = getenv('DB_PASSWORD');

    $dsn = "pgsql:host=$host;dbname=$dbname";

    try {
        // Connect to PostgreSQL database
        $pdo = new PDO($dsn, $user, $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

        // Fetch data from the employees table
        $stmt = $pdo->query("SELECT * FROM employees");
        $employees = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Start of table
        echo "<table id='employeesTable'>";
        echo "<tr><th>ID</th><th>First Name</th><th>Last Name</th><th>Department</th><th>Job Title</th><th>Email</th><th>Phone</th><th>Hire Date</th><th>Status</th></tr>";

        // Display the employees in the table
        foreach ($employees as $employee) {
            echo "<tr>
                    <td>{$employee['employee_id']}</td>
                    <td>{$employee['first_name']}</td>
                    <td>{$employee['last_name']}</td>
                    <td>{$employee['department']}</td>
                    <td>{$employee['job_title']}</td>
                    <td>{$employee['email']}</td>
                    <td>{$employee['phone_number']}</td>
                    <td>{$employee['hire_date']}</td>
                    <td>{$employee['status']}</td>
                  </tr>";
        }

        echo "</table>";

    } catch (PDOException $e) {
        echo "Error: " . $e->getMessage();
    }
    ?>

    </body>
    </html>
