apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.php.servicePort }}
      targetPort: {{ .Values.php.servicePort }}
  selector:
    app: php
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None
